### ISSUE TITLE
Test Project

### ISSUE THREAD

**Issue by sardara23** [thomasclaudiushuber/WPFandMVVM_TestDrivenDevelopment#1]
Pls upload the unit test project also as shown in videos. @thomasclaudiushuber

**Comment by thomasclaudiushuber** [comment]
Hi @sardara23 ,

you find all the projects of my courses under "Exercise Files" on the course homepage of Pluralsight.com.

Note that exercise files are not available if you access Pluralsight through the Pluralsight app for iOS, Android etc. Just browse to the website with your PC. I hope this helps, Thomas

**Comment by sardara23** [comment]
Thanks. Appreciate your efforts.
@thomasclaudiushuber
